# Mai City synthetic LiDAR dataset
# General Params
verbosity: 2
input_from_bag: true
use_lidar: &use_lidar true 
use_range_image: &use_range_image true
estimate_normal: &use_normal true
use_threadsafe_submap_collection: false
use_transform_caching: true
use_tf_transforms: true
transform_lookup_time: 0.1
global_frame_name: world
visualization_interval: -1.0
data_logging_interval: 0.0
print_timing_interval: -1.0
esdf_update_interval: 0.0 # 
max_input_queue_length: 1000
ros_spinning_threads: 8

lidar: # velodyne-64
  verbosity: 1
  width: 1024  # Px
  height: 64
  fov_up: 3.0  # deg
  fov_down: -25.0
  max_range: &max_range 60.0  # m
  min_range: &min_range 1.5
  ground_min_z: -1.0 # m
  smooth_thre_ratio: 0.05

id_tracker:
  type: single_tsdf
  verbosity: 1
  
  use_lidar: *use_lidar
  use_range_image: *use_range_image
  use_class_layer: false
  use_instance_classification: false
  integration_threads: 1 # slower, but can avoid SegFault
  use_color: false

  # map allocator
  voxel_size: 0.15
  truncation_distance: -2 # -3
  voxels_per_side: 16

  # freespace esdf mapping
  esdf_integrator_name: voxfield # select from voxblox, voxfield, fiesta and edt
  esdf_fiesta_patch: true
  esdf_fiesta_break: false
  finer_esdf_on: false
  fixed_band_esdf_on: false
  occ_voxel_size_ratio: &occ_voxel_size_ratio 0.866
  fixed_band_ratio: 2.0
  gradient_sign: -1.0
  esdf_max_distance_m: 5.0
  esdf_local_offset_x: 40
  esdf_local_offset_y: 40
  esdf_local_offset_z: 4

tsdf_integrator:  # different from those in voxblox
  # select from class_projective, class_raycast, class_adaptive, projective, raycast, adaptive, single_projective
  type: single_raycast
  verbosity: 2    

  use_range_image: *use_range_image
  use_lidar: *use_lidar   

  # Common
  # reliable_band_ratio * reliable_normal_ratio_thre should be smaller than 1
  apply_normal_refine_freespace: *use_normal
  curve_assumption: true
  behind_surface_reliable_band: true
  reliable_band_ratio: 5.0 # 5.0 , if set larger, tsdf error would be smaller but mesh error would be larger
  reliable_normal_ratio_thre: 0.1 # 0.2, if set larger, tsdf error would be larger but mesh error would be smaller
  # best setting used in voxblox
  use_weight_dropoff: true
  weight_dropoff_epsilon: -1.0 # if negative, means -k * voxel_size
  weight_reduction: true
  weight_reduction_exp: 2.0
  max_weight: 10000

  # Projective
  interpolation_method: adaptive  # nearest, bilinear, adaptive

  # Raycasting
  merged_raycasting: true # use "merged" raycast or not. "merged" raycast is faster but with larger tsdf error (almost no change of the mesh error)
  free_space_multi_threads: true # use multi-thread raycasting for the freespace submap independently, it should run faster if it is enabled
  freespace_carving_enabled: true # if true, slower but can deal with dynamic artifacts
  max_ray_length_m: *max_range
  min_ray_length_m: *min_range
  

visualization:  
  submaps:
    type: single_tsdf  # submaps, single_tsdf
    verbosity: 1
    color_mode: normals # submaps, instances, color, normals, classes, change, classification (means the fusion confidence)
    visualization_mode: all  # all, active, active_only, inactive, persistent
    submap_color_discretization: 30 # be same as the image's
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_occ_voxels: false
    visualize_slice: true
    visualize_free_space_tsdf: true
    visualize_free_space_esdf: true
    visualize_free_space_gsdf: true
    visualize_ground_tsdf: false
    visualize_bounding_volumes: true
    include_free_space: true
    slice_height: -0.5
    occ_voxel_size_ratio: *occ_voxel_size_ratio
  
  planning:
    verbosity: 1
    visualize_slice: true
    slice_resolution: 0.2
    slice_height: 0.0
  
  tracking:
    verbosity: 1
    visualize_tracking: true

# Available services:
# rosservice call /panoptic_mapper/save_map "file_path: '/media/yuepan/SeagateNew/1_data/mai_city/results/run1.panmap'"
# rosservice call /panoptic_mapper/save_esdf_map "file_path: '/media/yuepan/SeagateNew/1_data/mai_city/results/run1.esdf'" 
# rosservice call /panoptic_mapper/load_map "file_path: '/path/to/run1.panmap'" 
# rosservice call /panoptic_mapper/save_mesh "file_path: '/media/yuepan/SeagateNew/1_data/mai_city/results/mesh_test1.ply'" 
# rosservice call /panoptic_mapper/set_visualization_mode "color_mode: 'submaps'"
# rosservice call /panoptic_mapper/set_visualization_mode "visualization_mode: 'active'"

